/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-07-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class AccountHandler {
    public static Account insertNewAccount(string givenName) {
        // Account act=new Account(Name=givenName);
        // Database.SaveResult srAct=Database.insert(act,false);
        // if(srAct.isSuccess())
        // {
        //     System.debug('Successfully inserted contact. Contact ID: ' + srAct.getId());
        //     return act;
        // }
        // else{
        //     for(Database.Error err : srAct.getErrors()) {
        //         System.debug('The following error has occurred.');
        //         System.debug(err.getStatusCode() + ': ' + err.getMessage());
        //         System.debug('Contact fields that affected this error: ' + err.getFields());
                
        //  }
        //  return null;
        // }
        decimal a=10/0;
        
        return null;
    }

}